name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: |
          echo "Listing files:"
          ls -R

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz
          tar -xzf gitleaks_linux_x64.tar.gz
          chmod +x gitleaks

      - name: Run Gitleaks Scan
        run: |
          ./gitleaks detect --source . --verbose --redact --exit-code 1
